# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: See Asher Code
email: seeashercode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Asher learning to code with the desire to sail around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seeashercode.github.io" # the base hostname & protocol for your site
twitter_username: seeashercode
github_username:  seeashercode

# Build settings
markdown: kramdown
